(function(){
const $=id=>document.getElementById(id);if(!$('workTableBody'))return;const statusMap={unstarted:'未着手',current:'作業中',suspended:'中断',completed:'完了'};
function navigateShell(pageId, query){const params=new URLSearchParams(location.search);const shellMode=params.get('shell')==='1';const targetHash='#'+pageId+(query?('?'+query):'');if(shellMode&&window.parent){window.parent.location.hash=targetHash;return;}location.href='./'+targetHash;}
function toDate(v){if(!v)return null;if(typeof v.toDate==='function')return v.toDate();const d=new Date(v);return Number.isNaN(d.getTime())?null:d;}
function toMillis(v){const d=toDate(v);return d?d.getTime():0;}
function fmt(v){const d=toDate(v);return d?d.toLocaleString('ja-JP'):'-';}
const statusOf=r=>r.status||r.work?.status||'';
const num=v=>{const n=Number(v);return Number.isFinite(n)?n:0;};
function getClientCollection(db,clientId,name){if(!db)throw new Error('Firestore db is not initialized');if(!clientId)throw new Error('clientId is required');if(!name)throw new Error('collection name is required');return db.collection('clients').doc(clientId).collection(name);}
function getWorkId(r){return r.workId||r.work_id||r.id||'';}
function getPickingNo(r){return r.pickingNo||r.work?.pickingNo||r.work?.picking_no||r.work_id||r.workId||r.id||'';}
function getDestinationName(r){return r.destinationName||r.work?.destinationName||r.work?.recipient_name||'';}
function getTotalSkuCount(r){if(r.totalSkuCount!=null)return num(r.totalSkuCount);if(Array.isArray(r.details))return r.details.length;return 0;}
function getSkuDoneCount(r){if(Array.isArray(r.details))return r.details.filter(x=>x.completed_flag||x.itemStatus==='completed').length;if(statusOf(r)==='completed')return getTotalSkuCount(r);return '-';}
function getActualQtyTotal(r){if(r.actualQtyTotal!=null)return num(r.actualQtyTotal);if(r.work?.actualQtyTotal!=null)return num(r.work.actualQtyTotal);if(Array.isArray(r.details))return r.details.reduce((n,x)=>n+num(x.actual_qty??x.actualQty),0);return 0;}
function getTargetQtyTotal(r){if(r.targetQtyTotal!=null)return num(r.targetQtyTotal);if(r.work?.targetQtyTotal!=null)return num(r.work.targetQtyTotal);if(Array.isArray(r.details))return r.details.reduce((n,x)=>n+num(x.target_qty??x.targetQty),0);return 0;}
function getImportedAt(r){return r.createdAt||r.importedAt||r.import_date||r.work?.import_date;}
function getCompletedAt(r){return r.completedAt||r.completed_at||r.work?.completedAt||r.work?.completed_at;}
function getWorkerName(r){return r.completedWorkerName||r.currentWorkerName||r.work?.completed_worker_name||r.work?.current_worker_name||r.completedWorkerId||r.currentWorkerId||r.work?.current_worker_id||'-';}
function renderEmpty(msg){$('workTableBody').innerHTML='';$('listStatus').textContent=msg||'データはまだありません。';}
function renderError(userMessage,detail){$('workTableBody').innerHTML='';$('listStatus').textContent=userMessage;console.error('[inspection-list] detail',detail);}
function showInitError(error){const message=error?.message||String(error);let userMessage='初期設定に失敗しました。';if(message.includes('clientId'))userMessage='ログインユーザーに clientId が設定されていません。管理者に確認してください。';else if(message.includes('USER_NOT_REGISTERED')||message.includes('ユーザー設定'))userMessage='ログインユーザー設定が未作成です。管理者に確認してください。';else if(message.includes('permission-denied')||message.includes('PERMISSION_DENIED'))userMessage='利用権限またはテナント設定に問題があります。管理者に確認してください。';renderError(userMessage,message);}
function renderRows(rows){const isCompletedPage=document.body.dataset.page==='completed-list';$('workTableBody').innerHTML='';rows.forEach(r=>{const totalSku=getTotalSkuCount(r),skuDone=getSkuDoneCount(r),qa=getActualQtyTotal(r),qt=getTargetQtyTotal(r);const tr=document.createElement('tr');[getPickingNo(r),getDestinationName(r),statusMap[statusOf(r)]||statusOf(r),`${skuDone}/${totalSku}`,`${qa}/${qt}`,fmt(getImportedAt(r)),fmt(getCompletedAt(r)),getWorkerName(r)].forEach(v=>{const td=document.createElement('td');td.textContent=String(v);tr.appendChild(td);});const td=document.createElement('td');const workId=getWorkId(r);const openLink=document.createElement('a');openLink.className='btn-link';openLink.href='./#inspection?work_id='+encodeURIComponent(workId);openLink.textContent=isCompletedPage?'詳細を見る':'検品画面で開く';openLink.addEventListener('click',(e)=>{e.preventDefault();navigateShell('inspection','work_id='+encodeURIComponent(workId));});td.appendChild(openLink);tr.appendChild(td);$('workTableBody').appendChild(tr);});}
async function load(ctx){if(!ctx?.db){$('listStatus').textContent='Firebase未接続';return;}const kw=($('filterWorkId')?.value||'').trim();const worksRef=getClientCollection(ctx.db,ctx.clientId,'inspectionWorks');let rows=[];if(kw){const exact=await worksRef.doc(kw).get();if(exact.exists){rows=[{id:exact.id,...exact.data()}];}else{const byPickingNo=await worksRef.where('pickingNo','==',kw).limit(20).get();rows=byPickingNo.docs.map(d=>({id:d.id,...d.data()}));}}else{let q=worksRef;const allowed=(($('filterStatus')?.value)||'').split(',').filter(Boolean);if(allowed.length===1)q=q.where('status','==',allowed[0]);else if(allowed.length>1)q=q.where('status','in',allowed);const snap=await q.limit(300).get();rows=snap.docs.map(d=>({id:d.id,...d.data()}));}
rows=rows.filter(r=>!r.deleted_flag&&!r.work?.deleted_flag);const allowed=(($('filterStatus')?.value)||'').split(',').filter(Boolean);if(allowed.length)rows=rows.filter(r=>allowed.includes(statusOf(r)));const from=$('filterFrom')?.value,to=$('filterTo')?.value;function getFilterDateSource(r){if(document.body.dataset.page==='completed-list'){return r.completedAt||r.completed_at||r.updatedAt||r.updated_at||r.createdAt||r.created_at;}return r.createdAt||r.created_at||r.importedAt||r.imported_at||r.import_date||r.work?.import_date;}rows=rows.filter(r=>{const d=toDate(getFilterDateSource(r));const k=d?d.toISOString().slice(0,10):'';return (!from||k>=from)&&(!to||k<=to);});rows.sort((a,b)=>{const aKey=document.body.dataset.page==='completed-list'?toMillis(a.completedAt||a.updatedAt||a.updated_at||a.createdAt||a.created_at):toMillis(a.createdAt||a.created_at||a.updatedAt||a.updated_at||a.importedAt||a.imported_at);const bKey=document.body.dataset.page==='completed-list'?toMillis(b.completedAt||b.updatedAt||b.updated_at||b.createdAt||b.created_at):toMillis(b.createdAt||b.created_at||b.updatedAt||b.updated_at||b.importedAt||b.imported_at);return bKey-aKey;});if(rows.length===0){if(document.body.dataset.page==='completed-list')renderEmpty('検品完了データはまだありません。');else renderEmpty('未着手・中断・作業中の検品データはありません。');return;}renderRows(rows);$('listStatus').textContent=`${rows.length}件表示`;}
let currentCtx=null;$('searchButton')?.addEventListener('click',()=>load(currentCtx));$('reloadButton')?.addEventListener('click',()=>load(currentCtx));(async()=>{try{currentCtx=await window.appInit.ready(document.body.dataset.page);if(!currentCtx)return;console.log(`[${document.body.dataset.page||'inspection-list'}] context`,{uid:currentCtx.uid||currentCtx.userId,clientId:currentCtx.clientId,role:currentCtx.role});window.renderSidebar?.();await load(currentCtx);}catch(e){console.error('[inspection-list] init failed',e);showInitError(e);}})();
})();
