(()=>{
const state=window.inspectionState,$=id=>document.getElementById(id),statusMap={unstarted:'未着手',current:'作業中',suspended:'中断',completed:'完了'},syncMap={idle:['待機中','idle'],saving:['同期中','saving'],saved:['保存済み','saved'],failed:['保存失敗','failed']};
const DETAIL_TABLE_COLUMNS=[{key:'product_id',label:'品番',fallbackKeys:['productCode','sku','itemCode','品番']},{key:'product_name',label:'商品名',fallbackKeys:['productName','itemName','商品名']},{key:'size',label:'サイズ',fallbackKeys:['productSize','サイズ']},{key:'color',label:'カラー',fallbackKeys:['productColor','カラー']},{key:'category',label:'区分',fallbackKeys:['type','division','区分']},{key:'main_barcode',label:'JAN',fallbackKeys:['jan','scan_code','barcode','JAN']},{key:'qtyProgress',label:'個数',type:'progress'},{key:'result',label:'検品結果',type:'status'}];
const blank=()=>({work:{work_id:null,recipient_name:'',status:'unstarted',current_worker_id:null,completed_flag:false},details:[],recentScan:null,lastScannedCode:'',syncStatus:'idle',lock:{locked:false,reason:null,worker_id:null,started_at:null},qtyMode:{enabled:false,qty:1}});
const user=()=>window.auth?.currentUser?.email||window.auth?.currentUser?.uid||'unknown-user';
const playSound=(k)=>{try{if(window.AudioManager?.play)window.AudioManager.play(k);}catch(_){}};
const setJudge=(t,m,s='')=>{$('judgePanel').className=`inspection-judge inspection-judge--${t}`;$('mainMsgTxt').textContent=m;$('judgeSubText').textContent=s;};
const focusPickingNoInput=()=>requestAnimationFrame(()=>{$('pickingNoInput').focus();$('pickingNoInput').select();});
const focusJanInput=()=>requestAnimationFrame(()=>{if(!$('scanCodeInput').disabled){$('scanCodeInput').focus();$('scanCodeInput').select();}});
const rank=d=>!d.completed_flag&&d.actual_qty>0?0:d.actual_qty===0?1:d.completed_flag?2:3;
const pickValue=(obj,keys)=>{for(const k of keys||[]){if(obj&&obj[k]!=null&&obj[k]!=='')return obj[k];}return '';};
const display=value=>value==null||value===''?'-':value;

function render(){
 $('workId').textContent=display(state.work.work_id);$('recipientName').textContent=display(state.work.recipient_name);$('workStatus').textContent=statusMap[state.work.status]||state.work.status;$('workerId').textContent=display(state.work.current_worker_id);
 const skuDone=state.details.filter(d=>d.completed_flag).length,qa=state.details.reduce((n,d)=>n+d.actual_qty,0),qt=state.details.reduce((n,d)=>n+d.target_qty,0);
 $('skuProgress').textContent=`${skuDone} / ${state.details.length}`;$('qtyProgress').textContent=`${qa} / ${qt}`;$('judgeProgressText').textContent=state.details.length?`${qa} / ${qt}`:'';
 $('shipperName').textContent=display(pickValue(state.work,['shipperName','ownerName','clientName','荷主様名']));
 $('customerName').textContent=display(pickValue(state.work,['recipientName','recipient_name','customerName','deliveryName','得意先名','お届け先名']));
 $('inspectionCode').textContent=display(pickValue(state.work,['workId','work_id','pickingNo','picking_no'])||$('pickingNoInput').value);
 $('sentCode').textContent=display(state.lastScannedCode||state.recentScan?.scanCode||$('scanCodeInput').value);
 const [l,k]=syncMap[state.syncStatus]||syncMap.idle;$('syncStatus').textContent=l;$('syncStatus').className=`inspection-status-badge inspection-status-badge--${k}`;

 const sorted=[...state.details].sort((a,b)=>rank(a)-rank(b)||String(a.product_name||'').localeCompare(String(b.product_name||''),'ja'));
 const head=$('detailTableHead');const body=$('detailTableBody');head.replaceChildren();body.replaceChildren();
 DETAIL_TABLE_COLUMNS.forEach(c=>{const th=document.createElement('th');th.textContent=c.label;head.appendChild(th);});
 sorted.forEach(d=>{const tr=document.createElement('tr');let cls='detail-row--pending';if(state.recentScan?.detail?.detail_id===d.detail_id){cls='detail-row--recent';}else if(d.error_flag){cls='detail-row--error';}else if(d.completed_flag){cls='detail-row--done';}else if(d.actual_qty>0){cls='detail-row--partial';}tr.className=cls;
 DETAIL_TABLE_COLUMNS.forEach(c=>{const td=document.createElement('td');if(c.type==='progress')td.textContent=`${d.actual_qty} / ${d.target_qty}`;else if(c.type==='status')td.textContent=d.completed_flag?'完了':(d.actual_qty>0?'検品中':'未着手');else td.textContent=display(pickValue(d,[c.key,...(c.fallbackKeys||[])]));tr.appendChild(td);});body.appendChild(tr);});
 const r=state.recentScan?.detail;
 const panel=$('detailPanel');panel.replaceChildren();
 if(!r){const p=document.createElement('p');p.textContent='直近スキャン商品はありません。';panel.appendChild(p);}else{const dl=document.createElement('dl');const rows=[['品番',display(pickValue(r,['product_id','sku','itemCode','品番']))],['商品名',display(pickValue(r,['product_name','itemName','商品名']))],['サイズ',display(pickValue(r,['size','productSize','サイズ']))],['カラー',display(pickValue(r,['color','productColor','カラー']))],['区分',display(pickValue(r,['type','division','区分']))],['JAN',display(pickValue(r,['main_barcode','scan_code','barcode','JAN']))],['個数',`${r.actual_qty} / ${r.target_qty}`]];rows.forEach(([k,v])=>{const dt=document.createElement('dt');dt.textContent=k;const dd=document.createElement('dd');dd.textContent=v;dl.appendChild(dt);dl.appendChild(dd);});panel.appendChild(dl);}
}
async function persistAsync(reason,payload={}){state.syncStatus='saving';render();try{await window.saveInspectionState(state,{reason,payload});state.syncStatus='saved';render();return true;}catch(e){state.syncStatus='failed';state.lock={locked:true,reason:'sync-error',worker_id:null,started_at:new Date().toISOString()};setJudge('locked','同期失敗により停止中','再読取せず管理者へ確認してください');render();playSound('warning');return false;}}
function resetQtyMode(){state.qtyMode.enabled=false;state.qtyMode.qty=1;$('qtyModeToggle').checked=false;$('scanQtyInput').disabled=true;$('scanQtyInput').value='1';}
function resetToPickingNoInput(options={}){Object.assign(state,blank());$('pickingNoInput').disabled=false;$('scanCodeInput').disabled=true;resetQtyMode();$('pauseButton').disabled=true;$('resetButton').disabled=true;setJudge(options.completed?'complete':'idle',options.completed?'検品完了':'ピッキングNo.入力待ち',options.completed?'次のピッキングNo.を入力してください。':'ピッキングNo.を入力してください。');render();focusPickingNoInput();}
function confirmAction(message,onOk){const d=$('confirmDialog');const cleanup=()=>{ $('confirmOk').onclick=null;$('confirmCancel').onclick=null;d.close?.();};const focusBack=()=>{if(state.work.work_id&&!$('scanCodeInput').disabled)focusJanInput();else focusPickingNoInput();};$('confirmMessage').textContent=message;$('confirmOk').onclick=()=>{cleanup();onOk();};$('confirmCancel').onclick=()=>{cleanup();focusBack();};if(typeof d.showModal==='function')d.showModal();else if(window.confirm(message))$('confirmOk').onclick();else $('confirmCancel').onclick();}
async function loadPickingNo(v){const workId=String(v||'').trim();$('pickingNoInput').value=workId;if(!workId){resetToPickingNoInput();return;}setJudge('idle','読込中','');$('scanCodeInput').disabled=true;render();const loaded=await window.loadInspectionState(workId);if(!loaded){setJudge('error','該当なし','該当するピッキングNo.がありません');playSound('warning');focusPickingNoInput();return;}Object.assign(state,loaded);if(!state.details.length){setJudge('error','明細なし','このピッキングNo.には検品対象がありません');$('scanCodeInput').disabled=true;render();playSound('warning');focusPickingNoInput();return;}if(state.work.status==='completed'||state.work.completed_flag){state.work.status='completed';$('scanCodeInput').disabled=true;$('pauseButton').disabled=true;$('resetButton').disabled=true;setJudge('locked','完了済み','このピッキングNo.はすでに完了しています');render();playSound('warning');focusPickingNoInput();return;}const lock=await window.acquireWorkLock(workId,user());if(!lock.ok){setJudge('locked','他の作業者が作業中',`${lock.workerId||'-'} ${lock.startedAt||''}`);$('scanCodeInput').disabled=true;render();playSound('warning');focusPickingNoInput();return;}state.work.status='current';state.work.current_worker_id=user();state.lock={locked:false,reason:null,worker_id:null,started_at:null};$('scanCodeInput').disabled=false;$('pauseButton').disabled=false;$('resetButton').disabled=false;setJudge('working','検品中 未完了','残りの商品をスキャンしてください。');render();focusJanInput();}
async function runScan(){if(!state.work.work_id||state.details.length===0||$('scanCodeInput').disabled){setJudge('warning','ピッキングNo.入力待ち','ピッキングNo.を入力してください。');playSound('warning');focusPickingNoInput();return;}const raw=$('scanCodeInput').value.trim();if(!raw)return;$('scanCodeInput').value='';const qty=state.qtyMode.enabled?Number($('scanQtyInput').value):1;if(!Number.isInteger(qty)||qty<=0){setJudge('error','数量エラー','数量入力モードの値を確認してください。');playSound('ng');resetQtyMode();focusJanInput();return;}const detail=state.details.find(d=>d.scan_code===raw||d.main_barcode===raw||d.alt_code===raw);if(!detail){setJudge('error','読取エラー','該当するJANがありません。');playSound('ng');resetQtyMode();focusJanInput();return;}if(detail.actual_qty+qty>detail.target_qty){setJudge('error','指示数超過','数量を確認してください。');playSound('ng');resetQtyMode();focusJanInput();return;}detail.actual_qty+=qty;detail.completed_flag=detail.actual_qty===detail.target_qty;state.lastScannedCode=raw;state.recentScan={scanCode:raw,detail,isAlt:detail.main_barcode!==raw,at:Date.now()};const allDone=state.details.every(d=>d.completed_flag);if(allDone){state.work.status='completed';state.work.completed_flag=true;state.work.completed_at=new Date().toISOString();state.work.current_worker_id=null;setJudge('complete','検品完了','次のピッキングNo.を入力してください。');playSound('strong-complete');render();const ok=await persistAsync('scan',{scanCode:raw,detailId:detail.detail_id,qtyDelta:qty});if(ok)resetToPickingNoInput({completed:true});return;}setJudge('working','検品中 未完了','残りの商品をスキャンしてください。');playSound(detail.completed_flag?'complete':'ok');render();persistAsync('scan',{scanCode:raw,detailId:detail.detail_id,qtyDelta:qty});resetQtyMode();focusJanInput();}
async function init(){resetToPickingNoInput();$('headerUserName').textContent=user();const id=new URLSearchParams(location.search).get('work_id');if(id){$('pickingNoInput').value=id;await loadPickingNo(id);}}
$('loadPickingButton').addEventListener('click',()=>loadPickingNo($('pickingNoInput').value));$('pickingNoInput').addEventListener('keydown',e=>{if(e.key==='Enter'){e.preventDefault();loadPickingNo($('pickingNoInput').value);}});$('scanCodeInput').addEventListener('keydown',e=>{if(e.key==='Enter'){e.preventDefault();runScan();}});$('scanSubmitButton').addEventListener('click',runScan);$('qtyModeToggle').addEventListener('change',e=>{state.qtyMode.enabled=e.target.checked;$('scanQtyInput').disabled=!state.qtyMode.enabled;if(state.qtyMode.enabled)$('scanQtyInput').focus();else{$('scanQtyInput').value='1';focusJanInput();}});
$('pauseButton').addEventListener('click',()=>confirmAction('この作業を中断します。よろしいですか？',async()=>{state.work.status='suspended';state.work.suspended_at=new Date().toISOString();state.work.current_worker_id=null;const ok=await persistAsync('suspend');if(ok)resetToPickingNoInput();}));
$('resetButton').addEventListener('click',()=>confirmAction('この作業の検品実績をすべて0に戻します。\n実行してよろしいですか？',async()=>{state.details.forEach(d=>{d.actual_qty=0;d.completed_flag=false;});state.work.status='unstarted';state.work.completed_flag=false;state.work.current_worker_id=null;const ok=await persistAsync('reset');if(ok)resetToPickingNoInput();}));
init();})();
