(function(){
const $=id=>document.getElementById(id);if(!$('workTableBody'))return;const statusMap={unstarted:'未着手',current:'作業中',suspended:'中断',completed:'完了'};
const PAGE_SIZE=100;
const isCompletedPage=()=>document.body.dataset.page==='completed-list';
function navigateShell(pageId, query){const params=new URLSearchParams(location.search);const shellMode=params.get('shell')==='1';const targetHash='#'+pageId+(query?('?'+query):'');if(shellMode&&window.parent){window.parent.location.hash=targetHash;return;}location.href='./'+targetHash;}
function toDate(v){if(!v)return null;if(typeof v.toDate==='function')return v.toDate();const d=new Date(v);return Number.isNaN(d.getTime())?null:d;}
function toMillis(v){const d=toDate(v);return d?d.getTime():0;}
function fmt(v){const d=toDate(v);return d?d.toLocaleString('ja-JP'):'-';}
const statusOf=r=>r.status||r.work?.status||'';
const num=v=>{const n=Number(v);return Number.isFinite(n)?n:0;};
function getClientCollection(db,clientId,name){if(!db)throw new Error('Firestore db is not initialized');if(!clientId)throw new Error('clientId is required');if(!name)throw new Error('collection name is required');return db.collection('clients').doc(clientId).collection(name);}
function getWorkId(r){return r.workId||r.work_id||r.id||'';}
function getPickingNo(r){return r.pickingNo||r.work?.pickingNo||r.work?.picking_no||r.work_id||r.workId||r.id||'';}
function getDestinationName(r){return r.destinationName||r.work?.destinationName||r.work?.recipient_name||'';}
function getTotalSkuCount(r){if(r.totalSkuCount!=null)return num(r.totalSkuCount);if(Array.isArray(r.details))return r.details.length;return 0;}
function getSkuDoneCount(r){if(Array.isArray(r.details))return r.details.filter(x=>x.completed_flag||x.itemStatus==='completed').length;if(statusOf(r)==='completed')return getTotalSkuCount(r);return '-';}
function getActualQtyTotal(r){if(r.actualQtyTotal!=null)return num(r.actualQtyTotal);if(r.work?.actualQtyTotal!=null)return num(r.work.actualQtyTotal);if(Array.isArray(r.details))return r.details.reduce((n,x)=>n+num(x.actual_qty??x.actualQty),0);return 0;}
function getTargetQtyTotal(r){if(r.targetQtyTotal!=null)return num(r.targetQtyTotal);if(r.work?.targetQtyTotal!=null)return num(r.work.targetQtyTotal);if(Array.isArray(r.details))return r.details.reduce((n,x)=>n+num(x.target_qty??x.targetQty),0);return 0;}
function getImportedAt(r){return r.createdAt||r.importedAt||r.import_date||r.work?.import_date;}
function getCompletedAt(r){return r.completedAt||r.completed_at||r.work?.completedAt||r.work?.completed_at;}
function getWorkerName(r){return r.completedWorkerName||r.currentWorkerName||r.work?.completed_worker_name||r.work?.current_worker_name||r.completedWorkerId||r.currentWorkerId||r.work?.current_worker_id||'-';}
function renderEmpty(msg){$('workTableBody').innerHTML='';$('listStatus').textContent=msg||'データはまだありません。';}
function renderError(userMessage,detail){$('workTableBody').innerHTML='';$('listStatus').textContent=userMessage;console.error('[inspection-list] detail',detail);}
function showInitError(error){const message=error?.message||String(error);let userMessage='初期設定に失敗しました。';if(message.includes('clientId'))userMessage='ログインユーザーに clientId が設定されていません。管理者に確認してください。';else if(message.includes('USER_NOT_REGISTERED')||message.includes('ユーザー設定'))userMessage='ログインユーザー設定が未作成です。管理者に確認してください。';else if(message.includes('permission-denied')||message.includes('PERMISSION_DENIED'))userMessage='利用権限またはテナント設定に問題があります。管理者に確認してください。';renderError(userMessage,message);}
function renderRows(rows){const completedPage=isCompletedPage();$('workTableBody').innerHTML='';rows.forEach(r=>{const totalSku=getTotalSkuCount(r),skuDone=getSkuDoneCount(r),qa=getActualQtyTotal(r),qt=getTargetQtyTotal(r);const tr=document.createElement('tr');[getPickingNo(r),getDestinationName(r),statusMap[statusOf(r)]||statusOf(r),`${skuDone}/${totalSku}`,`${qa}/${qt}`,fmt(getImportedAt(r)),fmt(getCompletedAt(r)),getWorkerName(r)].forEach(v=>{const td=document.createElement('td');td.textContent=String(v);tr.appendChild(td);});const td=document.createElement('td');const workId=getWorkId(r);const openLink=document.createElement('a');openLink.className='btn-link';openLink.href='./#inspection?work_id='+encodeURIComponent(workId);openLink.textContent=completedPage?'詳細を見る':'検品画面で開く';openLink.addEventListener('click',(e)=>{e.preventDefault();navigateShell('inspection','work_id='+encodeURIComponent(workId));});td.appendChild(openLink);tr.appendChild(td);$('workTableBody').appendChild(tr);});}
function ensureNextButton(){let btn=$('nextPageButton');if(btn)return btn;btn=document.createElement('button');btn.id='nextPageButton';btn.type='button';btn.textContent='次ページ';btn.disabled=true;$('reloadButton')?.insertAdjacentElement('afterend',btn);return btn;}
// FirestoreのorderByは対象フィールドがない既存docを返さない。
// 本番適用前に docs/firestore-retention.md の inspectionWorks 日付フィールド補完を完了すること。
function getDateField(){return isCompletedPage()?'completedAt':'createdAt';}
function getCompletedSortDate(r){return r.completedAt||r.completed_at||r.work?.completedAt||r.work?.completed_at;}
function getFilterDateSource(r){if(isCompletedPage())return getCompletedSortDate(r);return r.createdAt||r.created_at||r.importedAt||r.imported_at||r.import_date||r.work?.import_date;}
function getSortMillis(r){if(isCompletedPage())return toMillis(getCompletedSortDate(r));return toMillis(r.createdAt||r.created_at||r.updatedAt||r.updated_at||r.importedAt||r.imported_at);}
function dayStart(value){const d=new Date(`${value}T00:00:00`);return Number.isNaN(d.getTime())?null:d;}
function dayEndExclusive(value){const d=dayStart(value);if(!d)return null;d.setDate(d.getDate()+1);return d;}
function applySafetyFilters(rows){const allowed=(($('filterStatus')?.value)||'').split(',').filter(Boolean);const from=$('filterFrom')?.value,to=$('filterTo')?.value;return rows.filter(r=>!r.deleted_flag&&!r.work?.deleted_flag).filter(r=>!allowed.length||allowed.includes(statusOf(r))).filter(r=>{const d=toDate(getFilterDateSource(r));const k=d?d.toISOString().slice(0,10):'';return (!from||k>=from)&&(!to||k<=to);});}
let currentCtx=null,lastCursor=null,hasNext=false,currentRows=[],lastMode='list';
async function fetchListPage(ctx,{append=false}={}){const worksRef=getClientCollection(ctx.db,ctx.clientId,'inspectionWorks');let q=worksRef;const allowed=isCompletedPage()?['completed']:(($('filterStatus')?.value)||'').split(',').filter(Boolean);if(allowed.length===1)q=q.where('status','==',allowed[0]);else if(allowed.length>1)q=q.where('status','in',allowed);const dateField=getDateField();const from=$('filterFrom')?.value,to=$('filterTo')?.value;if(from){const d=dayStart(from);if(d)q=q.where(dateField,'>=',d);}if(to){const d=dayEndExclusive(to);if(d)q=q.where(dateField,'<',d);}q=q.orderBy(dateField,'desc').limit(PAGE_SIZE+1);if(append&&lastCursor)q=q.startAfter(lastCursor);const snap=await q.get();const docs=snap.docs.slice(0,PAGE_SIZE);lastCursor=docs.length?docs[docs.length-1]:lastCursor;hasNext=snap.docs.length>PAGE_SIZE;return docs.map(d=>({id:d.id,...d.data()}));}
async function fetchKeywordRows(ctx,kw){const worksRef=getClientCollection(ctx.db,ctx.clientId,'inspectionWorks');const exact=await worksRef.doc(kw).get();if(exact.exists)return [{id:exact.id,...exact.data()}];const byPickingNo=await worksRef.where('pickingNo','==',kw).limit(20).get();return byPickingNo.docs.map(d=>({id:d.id,...d.data()}));}
function updateStatus(){const btn=ensureNextButton();btn.hidden=lastMode!=='list';btn.disabled=!hasNext;$('listStatus').textContent=`${currentRows.length}件表示（1ページ最大${PAGE_SIZE}件）${hasNext?' - 次ページがあります':''}`;}
async function load(ctx,{append=false}={}){if(!ctx?.db){$('listStatus').textContent='Firebase未接続';return;}const kw=($('filterWorkId')?.value||'').trim();let rows=[];if(kw){lastMode='keyword';lastCursor=null;hasNext=false;rows=await fetchKeywordRows(ctx,kw);currentRows=applySafetyFilters(rows);}else{lastMode='list';if(!append){lastCursor=null;currentRows=[];}rows=await fetchListPage(ctx,{append});currentRows=applySafetyFilters(append?currentRows.concat(rows):rows);}currentRows.sort((a,b)=>getSortMillis(b)-getSortMillis(a));if(currentRows.length===0){if(document.body.dataset.page==='completed-list')renderEmpty('このページに表示可能な検品完了データはありません。');else renderEmpty('このページに表示可能な未着手・中断・作業中データはありません。');const btn=ensureNextButton();btn.hidden=lastMode!=='list';btn.disabled=!hasNext;if(hasNext)$('listStatus').textContent+=` 次ページにデータがある可能性があります。（1ページ最大${PAGE_SIZE}件）`;return;}renderRows(currentRows);updateStatus();}
$('searchButton')?.addEventListener('click',()=>load(currentCtx));$('reloadButton')?.addEventListener('click',()=>load(currentCtx));ensureNextButton().addEventListener('click',()=>load(currentCtx,{append:true}));(async()=>{try{currentCtx=await window.appInit.ready(document.body.dataset.page);if(!currentCtx)return;console.log(`[${document.body.dataset.page||'inspection-list'}] context`,{uid:currentCtx.uid||currentCtx.userId,clientId:currentCtx.clientId,role:currentCtx.role});window.renderSidebar?.();await load(currentCtx);}catch(e){console.error('[inspection-list] init failed',e);showInitError(e);}})();
})();
